# Generated by Django 4.0 on 2021-12-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='grupo',
            field=models.CharField(choices=[(1, 'F1401'), (2, 'F1402'), (3, 'F1403'), (4, 'F1404'), (5, 'F1405')], max_length=20),
        ),
    ]
