# Generated by Django 4.0 on 2021-12-30 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seguridad', '0002_alter_estudiante_grupo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
