# Generated by Django 4.0 on 2022-01-10 02:57

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('facultad', models.IntegerField(choices=[(1, 'Facultad 1'), (2, 'Facultad 2'), (3, 'Facultad 3'), (4, 'Facultad 4'), (5, 'FTE'), (6, 'CITEC')])),
                ('grupo', models.IntegerField(choices=[(1, 'G-01'), (2, 'G-02'), (3, 'G-03'), (4, 'G-04'), (5, 'G-05')])),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
