# Generated by Django 4.0 on 2022-01-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='cambiar_pass',
            field=models.BooleanField(default=False),
        ),
    ]
