# Generated by Django 4.0 on 2021-12-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='facultad',
            field=models.IntegerField(choices=[(1, 'Facultad 1'), (2, 'Facultad 2'), (3, 'Facultad 3'), (4, 'Facultad 4'), (5, 'FTE'), (6, 'CITEC')], max_length=20),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='grupo',
            field=models.IntegerField(choices=[(1, 'F1401'), (2, 'F1402'), (3, 'F1403'), (4, 'F1404'), (5, 'F1405')], max_length=20),
        ),
    ]
