# Generated by Django 4.0 on 2022-01-10 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiante', '0005_alter_estudiante_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='foto',
        ),
    ]
